name: Tests

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.1

      - name: Build and test Zig Project
        run: zig build

      - name: Build and test Zig Project 1
        run: zig build test

      - name: Build and test Zig Project 2
        run: zig build examples
